name: Azure-docker-build-Workflow
on:
  workflow_call:
    secrets:
      ORG_AZURE_CREDENTIALS:
        required: true
      ORG_REGISTRY_USERNAME:
        required: true
      ORG_REGISTRY_LOGIN_SERVER:
         required: true
      ORG_REGISTRY_PASSWORD:
         required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # checkout the repo
        - name: 'Checkout GitHub repo'
          uses: actions/checkout@v3 
        - uses: elstudio/action-install-azure-cli@v1
                
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.ORG_AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ORG_REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.ORG_REGISTRY_USERNAME }}
            password: ${{ secrets.ORG_REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.ORG_REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.ORG_REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
      
