name: Azure-docker-build-push
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      ORG_AZURE_CREDENTIALS:
        required: true
      ORG_REGISTRY_USERNAME:
        required: true
      ORG_REGISTRY_PASSWORD:
         required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
            
        - name: install pcregrep 
          run: |
            sudo apt install pcregrep
            
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '14.x'
          
        - name: Setup latest NPM
          run: npm install -g npm@latest
          
        - name: Set permissions
          run: |
            git config --global url."https://${{ secrets.ORG_NPM_INSTALL }}@github.com/".insteadOf ssh://git@github.com/
        
        - name: Get dependencies
          run: |
            cd /home/runner/work/ncms-user/ncms-user/01_SourceCode/app/
            npm ci --production
        
        - uses: elstudio/action-install-azure-cli@v1
                
        - name: Login via Azure CLI
          uses: azure/login@v1
          with:
            creds: ${{ secrets.ORG_AZURE_CREDENTIALS }}
        
        - name: azure login
          uses: azure/docker-login@v1
          with:
            login-server: numogateway.azurecr.io
            username: ${{ secrets.ORG_REGISTRY_USERNAME }}
            password: ${{ secrets.ORG_REGISTRY_PASSWORD }}
            
        - name: install npm dependencies   
          run: |
            cd 01_SourceCode/app
            npm install
            
        - name: update tag,name and build,push
          run: |
            export CONTAINER_NAME=$(cat docker-compose.yml | pcregrep -o1 'container_name: ([^\s]+)')
            export DOCKER_TAG=$(basename ${{ inputs.tag }})
            cd 01_SourceCode
            docker build . -t numogateway.azurecr.io/${CONTAINER_NAME}:$DOCKER_TAG
            docker push numogateway.azurecr.io/${CONTAINER_NAME}:$DOCKER_TAG
