name: Azure-docker-build-push
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      ORG_NPM_INSTALL:
        required: true
      ORG_AZURE_CREDENTIALS:
        required: true
      ORG_REGISTRY_USERNAME:
        required: true
      ORG_REGISTRY_PASSWORD:
         required: true
jobs:
  call-checkmycode:
    uses: ncmsdev/numo-builder/.github/workflows/checkmycode.yml@main
    secrets:
      ORG_NPM_INSTALL: ${{ secrets.ORG_NPM_INSTALL }}

  build:
    needs: [call-checkmycode]
    runs-on: ubuntu-latest
    steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          with:
            persist-credentials: false
            
        - name: install pcregrep 
          run: |
            sudo apt install pcregrep
            
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '14.x'
          
        - name: Setup latest NPM
          run: npm install -g npm@latest
        
        - name: Set permissions
          run: |
            git config --global url."https://${{ secrets.ORG_NPM_INSTALL }}@github.com/".insteadOf ssh://git@github.com/
        
        - name: Get dependencies
          run: npm ci --production
          
        - uses: elstudio/action-install-azure-cli@v1
                
        - name: Login via Azure CLI
          run: sudo az login --service-principal -u 350cb86d-5f21-4882-94be-2af475061e77 -p "${{ secrets.AZ_SERVICE_PASSWORD }}" --tenant ${{ secrets.AZ_TENANT }}
        
        - name: azure login
          uses: azure/docker-login@v1
          with:
            login-server: numogateway.azurecr.io
            username: ${{ secrets.ORG_REGISTRY_USERNAME }}
            password: ${{ secrets.ORG_REGISTRY_PASSWORD }}
            
        - name: update tag,name and build,push
          run: |
            export CONTAINER_NAME=$(cat docker-compose.yml | pcregrep -o1 'container_name: ([^\s]+)')
            export DOCKER_TAG=$(basename ${{ inputs.tag }})
            find . -name '*function.json' -print0 | xargs -0 sed -i 's/function/anonymous/g' || true
            docker build . -t numogateway.azurecr.io/${CONTAINER_NAME}:$DOCKER_TAG
            docker push numogateway.azurecr.io/${CONTAINER_NAME}:$DOCKER_TAG
      
