name: Azure-docker-deploy-Workflow
on:
  workflow_call:
    secrets:
      ORG_AZURE_CREDENTIALS:
        required: true
      ORG_REGISTRY_USERNAME:
        required: true
      ORG_REGISTRY_LOGIN_SERVER:
         required: true
      ORG_REGISTRY_PASSWORD:
         required: true
      ORG_RESOURCE_GROUP:
         required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: elstudio/action-install-azure-cli@v1
                
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.ORG_AZURE_CREDENTIALS }}
            
        - name: to pull docker image
          run: docker pull numotrials.azurecr.io/ocppserver:v1.0.0
