name: Deploy-image-on-devfusion
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        - name: 'docker pull'
          run: docker pull numotrials.azurecr.io/ocppserver:v1.0.0
