name: secret-scan

on: workflow_call

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub repo'
        uses: actions/checkout@v3
      - name: Scan for secrets
        run: |
            docker run -v ./trivycache:/root/.cache/trivy -v .:/inputrepo aquasec/trivy \
            --scanners secret --exit-code 1 repo /inputrepo
